service: sabbag-ris-api-backend

frameworkVersion: "4"

plugins:
  - serverless-python-requirements
  - serverless-dotenv-plugin

custom:
  dotenv:
    path: .env.${opt:stage, 'dev'}

  pythonRequirements:
    dockerizePip: true
    slim: true
    strip: true
    noDeploy:
      - boto3
      - botocore
      - docutils
      - jmespath
      - pip
      - python-dateutil
      - s3transfer
      - setuptools
      - six
      - urllib3
      - wheel

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  stage: ${opt:stage, 'dev'}

  environment:
    JWT_SECRET: ${env:JWT_SECRET}
    DB_MEDILAB_SECRET_ARN: ${env:DB_MEDILAB_SECRET_ARN}
    REDIS_HOST: ${env:REDIS_HOST}
    REDIS_PORT: ${env:REDIS_PORT}
    REDIS_IDENTIFIER: ${env:REDIS_IDENTIFIER}
    DICOM_URL: ${env:DICOM_URL}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - secretsmanager:GetSecretValue
      Resource: ${env:DB_MEDILAB_SECRET_ARN}

    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: "*"

    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
        - s3:PutObjectAcl
      Resource: arn:aws:s3:::sabbag-pdr-bucket-dev/*

package:
  patterns:
    - "!**"
    - "src/**"
    - "requirements.txt"

functions:
  get_studies:
    handler: src/handlers/get_studies_handler.lambda_handler
    events:
      - httpApi:
          path: /studies/{patient_id}
          method: get

  get_report:
    handler: src/handlers/get_report_handler.lambda_handler
    events:
      - httpApi:
          path: /report/{report_id}
          method: get

  get_dicom:
    handler: src/handlers/get_dicom_url_handler.lambda_handler
    events:
      - httpApi:
          path: /dicom
          method: post

  otp_options:
    handler: src/handlers/otp_handlers.otp_options_handler
    events:
      - httpApi:
          path: /recovery/options
          method: post

  otp_request:
    handler: src/handlers/otp_handlers.otp_request_handler
    events:
      - httpApi:
          path: /recovery/request
          method: post

  otp_verify:
    handler: src/handlers/otp_handlers.otp_verify_handler
    events:
      - httpApi:
          path: /recovery/verify
          method: post
