service: sabbag-ris-api-backend

frameworkVersion: "4"

plugins:
  - serverless-python-requirements
  - serverless-dotenv-plugin

custom:
  dotenv:
    path: .env.${opt:stage, 'dev'}

  pythonRequirements:
    dockerizePip: true
    slim: true
    strip: true
    noDeploy:
      - boto3
      - botocore
      - docutils
      - jmespath
      - pip
      - python-dateutil
      - s3transfer
      - setuptools
      - six
      - urllib3
      - wheel

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  stage: ${opt:stage, 'dev'}

  environment:
    JWT_SECRET: ${env:JWT_SECRET}
    DB_MEDILAB_SECRET_ARN: ${env:DB_MEDILAB_SECRET_ARN}
    REDIS_HOST: ${env:REDIS_HOST}
    REDIS_PORT: ${env:REDIS_PORT}
    REDIS_IDENTIFIER: ${env:REDIS_IDENTIFIER}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - secretsmanager:GetSecretValue
      Resource: ${env:DB_MEDILAB_SECRET_ARN}

    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: "*"

package:
  patterns:
    - "!**"
    - "src/**"
    - "requirements.txt"

functions:
  loginPaciente:
    handler: src/handlers/login_patient.lambda_handler
    events:
      - httpApi:
          path: /login/patient
          method: post

  loginUser:
    handler: src/handlers/login_user.lambda_handler
    events:
      - httpApi:
          path: /login/user
          method: post

  patientPasswordRecoveryOptions:
    handler: src/handlers/patient_password_recovery_options.lambda_handler
    events:
      - httpApi:
          path: /patient/recovery/options
          method: post

  patientPasswordRecoveryRequest:
    handler: src/handlers/patient_password_recovery_request.lambda_handler
    events:
      - httpApi:
          path: /patient/recovery/request
          method: post

  patientPasswordRecoveryVerify:
    handler: src/handlers/patient_password_recovery_verify.lambda_handler
    events:
      - httpApi:
          path: /patient/recovery/verify
          method: post

  patientPasswordRecoveryReset:
    handler: src/handlers/patient_password_recovery_reset.lambda_handler
    events:
      - httpApi:
          path: /patient/recovery/reset
          method: post

  list_patient_studies:
    handler: src/handlers/list_patient_studies.lambda_handler
    events:
      - httpApi:
          path: /studies/{patient_id}
          method: get
